export const platforms = [
  { value: "spotify", label: "Spotify" },
  { value: "apple-music", label: "Apple Music" },
  { value: "youtube-music", label: "YouTube Music" },
  { value: "amazon-music", label: "Amazon Music" },
  { value: "deezer", label: "Deezer" },
  { value: "tidal", label: "Tidal" },
  { value: "soundcloud", label: "SoundCloud" },
  { value: "pandora", label: "Pandora" },
  { value: "iheartradio", label: "iHeartRadio" },
  { value: "napster", label: "Napster" },
  { value: "qobuz", label: "Qobuz" },
  { value: "bandcamp", label: "Bandcamp" },
  { value: "audiomack", label: "Audiomack" },
  { value: "anghami", label: "Anghami" },
  { value: "jiosaavn", label: "JioSaavn" },
  { value: "gaana", label: "Gaana" },
  { value: "wynk", label: "Wynk Music" },
  { value: "yandex-music", label: "Yandex Music" },
  { value: "vk-music", label: "VK Music" },
  { value: "netease", label: "NetEase Cloud Music" },
  { value: "qq-music", label: "QQ Music" },
  { value: "kugou", label: "Kugou Music" },
  { value: "kuwo", label: "Kuwo Music" },
  { value: "line-music", label: "LINE MUSIC" },
  { value: "kkbox", label: "KKBOX" },
  { value: "joox", label: "JOOX" },
  { value: "boomplay", label: "Boomplay" },
  { value: "mdundo", label: "Mdundo" },
  { value: "audiius", label: "Audius" },
  { value: "mixcloud", label: "Mixcloud" }
];
