export const PROFILE_COUNTRIES = [
  { code: "AF", name: "Afghanistan",                    label: "🇦🇫 Afganistán",              dial: "+93"  },
  { code: "AL", name: "Albania",                        label: "🇦🇱 Albania",                 dial: "+355" },
  { code: "DE", name: "Germany",                        label: "🇩🇪 Alemania",                dial: "+49"  },
  { code: "AD", name: "Andorra",                        label: "🇦🇩 Andorra",                 dial: "+376" },
  { code: "AO", name: "Angola",                         label: "🇦🇴 Angola",                  dial: "+244" },
  { code: "AG", name: "Antigua and Barbuda",            label: "🇦🇬 Antigua y Barbuda",       dial: "+1"   },
  { code: "SA", name: "Saudi Arabia",                   label: "🇸🇦 Arabia Saudita",          dial: "+966" },
  { code: "DZ", name: "Algeria",                        label: "🇩🇿 Argelia",                 dial: "+213" },
  { code: "AR", name: "Argentina",                      label: "🇦🇷 Argentina",               dial: "+54"  },
  { code: "AM", name: "Armenia",                        label: "🇦🇲 Armenia",                 dial: "+374" },
  { code: "AU", name: "Australia",                      label: "🇦🇺 Australia",               dial: "+61"  },
  { code: "AT", name: "Austria",                        label: "🇦🇹 Austria",                 dial: "+43"  },
  { code: "AZ", name: "Azerbaijan",                     label: "🇦🇿 Azerbaiyán",              dial: "+994" },
  { code: "BS", name: "Bahamas",                        label: "🇧🇸 Bahamas",                 dial: "+1"   },
  { code: "BH", name: "Bahrain",                        label: "🇧🇭 Baréin",                  dial: "+973" },
  { code: "BD", name: "Bangladesh",                     label: "🇧🇩 Bangladés",               dial: "+880" },
  { code: "BB", name: "Barbados",                       label: "🇧🇧 Barbados",                dial: "+1"   },
  { code: "BE", name: "Belgium",                        label: "🇧🇪 Bélgica",                 dial: "+32"  },
  { code: "BZ", name: "Belize",                         label: "🇧🇿 Belice",                  dial: "+501" },
  { code: "BJ", name: "Benin",                          label: "🇧🇯 Benín",                   dial: "+229" },
  { code: "BY", name: "Belarus",                        label: "🇧🇾 Bielorrusia",             dial: "+375" },
  { code: "MM", name: "Myanmar",                        label: "🇲🇲 Birmania",                dial: "+95"  },
  { code: "BO", name: "Bolivia",                        label: "🇧🇴 Bolivia",                 dial: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina",         label: "🇧🇦 Bosnia y Herzegovina",    dial: "+387" },
  { code: "BW", name: "Botswana",                       label: "🇧🇼 Botsuana",                dial: "+267" },
  { code: "BR", name: "Brazil",                         label: "🇧🇷 Brasil",                  dial: "+55"  },
  { code: "BN", name: "Brunei",                         label: "🇧🇳 Brunéi",                  dial: "+673" },
  { code: "BG", name: "Bulgaria",                       label: "🇧🇬 Bulgaria",                dial: "+359" },
  { code: "BF", name: "Burkina Faso",                   label: "🇧🇫 Burkina Faso",            dial: "+226" },
  { code: "BI", name: "Burundi",                        label: "🇧🇮 Burundi",                 dial: "+257" },
  { code: "BT", name: "Bhutan",                         label: "🇧🇹 Bután",                   dial: "+975" },
  { code: "CV", name: "Cape Verde",                     label: "🇨🇻 Cabo Verde",              dial: "+238" },
  { code: "KH", name: "Cambodia",                       label: "🇰🇭 Camboya",                 dial: "+855" },
  { code: "CM", name: "Cameroon",                       label: "🇨🇲 Camerún",                 dial: "+237" },
  { code: "CA", name: "Canada",                         label: "🇨🇦 Canadá",                  dial: "+1"   },
  { code: "QA", name: "Qatar",                          label: "🇶🇦 Catar",                   dial: "+974" },
  { code: "TD", name: "Chad",                           label: "🇹🇩 Chad",                    dial: "+235" },
  { code: "CL", name: "Chile",                          label: "🇨🇱 Chile",                   dial: "+56"  },
  { code: "CN", name: "China",                          label: "🇨🇳 China",                   dial: "+86"  },
  { code: "CY", name: "Cyprus",                         label: "🇨🇾 Chipre",                  dial: "+357" },
  { code: "VA", name: "Vatican City",                   label: "🇻🇦 Ciudad del Vaticano",     dial: "+379" },
  { code: "CO", name: "Colombia",                       label: "🇨🇴 Colombia",                dial: "+57"  },
  { code: "KM", name: "Comoros",                        label: "🇰🇲 Comoras",                 dial: "+269" },
  { code: "CG", name: "Republic of the Congo",          label: "🇨🇬 Congo (Rep.)",            dial: "+242" },
  { code: "CD", name: "Democratic Republic of the Congo", label: "🇨🇩 Congo (RD)",           dial: "+243" },
  { code: "KP", name: "North Korea",                    label: "🇰🇵 Corea del Norte",         dial: "+850" },
  { code: "KR", name: "South Korea",                    label: "🇰🇷 Corea del Sur",           dial: "+82"  },
  { code: "CR", name: "Costa Rica",                     label: "🇨🇷 Costa Rica",              dial: "+506" },
  { code: "CI", name: "Ivory Coast",                    label: "🇨🇮 Costa de Marfil",         dial: "+225" },
  { code: "HR", name: "Croatia",                        label: "🇭🇷 Croacia",                 dial: "+385" },
  { code: "CU", name: "Cuba",                           label: "🇨🇺 Cuba",                    dial: "+53"  },
  { code: "DK", name: "Denmark",                        label: "🇩🇰 Dinamarca",               dial: "+45"  },
  { code: "DJ", name: "Djibouti",                       label: "🇩🇯 Yibuti",                  dial: "+253" },
  { code: "DM", name: "Dominica",                       label: "🇩🇲 Dominica",                dial: "+1"   },
  { code: "EC", name: "Ecuador",                        label: "🇪🇨 Ecuador",                 dial: "+593" },
  { code: "EG", name: "Egypt",                          label: "🇪🇬 Egipto",                  dial: "+20"  },
  { code: "SV", name: "El Salvador",                    label: "🇸🇻 El Salvador",             dial: "+503" },
  { code: "AE", name: "United Arab Emirates",           label: "🇦🇪 Emiratos Árabes Unidos",  dial: "+971" },
  { code: "ER", name: "Eritrea",                        label: "🇪🇷 Eritrea",                 dial: "+291" },
  { code: "SK", name: "Slovakia",                       label: "🇸🇰 Eslovaquia",              dial: "+421" },
  { code: "SI", name: "Slovenia",                       label: "🇸🇮 Eslovenia",               dial: "+386" },
  { code: "ES", name: "Spain",                          label: "🇪🇸 España",                  dial: "+34"  },
  { code: "US", name: "United States",                  label: "🇺🇸 Estados Unidos",          dial: "+1"   },
  { code: "EE", name: "Estonia",                        label: "🇪🇪 Estonia",                 dial: "+372" },
  { code: "SZ", name: "Eswatini",                       label: "🇸🇿 Esuatini",                dial: "+268" },
  { code: "ET", name: "Ethiopia",                       label: "🇪🇹 Etiopía",                 dial: "+251" },
  { code: "FJ", name: "Fiji",                           label: "🇫🇯 Fiyi",                    dial: "+679" },
  { code: "PH", name: "Philippines",                    label: "🇵🇭 Filipinas",               dial: "+63"  },
  { code: "FI", name: "Finland",                        label: "🇫🇮 Finlandia",               dial: "+358" },
  { code: "FR", name: "France",                         label: "🇫🇷 Francia",                 dial: "+33"  },
  { code: "GA", name: "Gabon",                          label: "🇬🇦 Gabón",                   dial: "+241" },
  { code: "GM", name: "Gambia",                         label: "🇬🇲 Gambia",                  dial: "+220" },
  { code: "GE", name: "Georgia",                        label: "🇬🇪 Georgia",                 dial: "+995" },
  { code: "GH", name: "Ghana",                          label: "🇬🇭 Ghana",                   dial: "+233" },
  { code: "GD", name: "Grenada",                        label: "🇬🇩 Granada",                 dial: "+1"   },
  { code: "GR", name: "Greece",                         label: "🇬🇷 Grecia",                  dial: "+30"  },
  { code: "GT", name: "Guatemala",                      label: "🇬🇹 Guatemala",               dial: "+502" },
  { code: "GN", name: "Guinea",                         label: "🇬🇳 Guinea",                  dial: "+224" },
  { code: "GQ", name: "Equatorial Guinea",              label: "🇬🇶 Guinea Ecuatorial",       dial: "+240" },
  { code: "GW", name: "Guinea-Bissau",                  label: "🇬🇼 Guinea-Bisáu",            dial: "+245" },
  { code: "GY", name: "Guyana",                         label: "🇬🇾 Guyana",                  dial: "+592" },
  { code: "HT", name: "Haiti",                          label: "🇭🇹 Haití",                   dial: "+509" },
  { code: "HN", name: "Honduras",                       label: "🇭🇳 Honduras",                dial: "+504" },
  { code: "HU", name: "Hungary",                        label: "🇭🇺 Hungría",                 dial: "+36"  },
  { code: "IN", name: "India",                          label: "🇮🇳 India",                   dial: "+91"  },
  { code: "ID", name: "Indonesia",                      label: "🇮🇩 Indonesia",               dial: "+62"  },
  { code: "IQ", name: "Iraq",                           label: "🇮🇶 Irak",                    dial: "+964" },
  { code: "IR", name: "Iran",                           label: "🇮🇷 Irán",                    dial: "+98"  },
  { code: "IE", name: "Ireland",                        label: "🇮🇪 Irlanda",                 dial: "+353" },
  { code: "IS", name: "Iceland",                        label: "🇮🇸 Islandia",                dial: "+354" },
  { code: "MH", name: "Marshall Islands",               label: "🇲🇭 Islas Marshall",          dial: "+692" },
  { code: "SB", name: "Solomon Islands",                label: "🇸🇧 Islas Salomón",           dial: "+677" },
  { code: "IL", name: "Israel",                         label: "🇮🇱 Israel",                  dial: "+972" },
  { code: "IT", name: "Italy",                          label: "🇮🇹 Italia",                  dial: "+39"  },
  { code: "JM", name: "Jamaica",                        label: "🇯🇲 Jamaica",                 dial: "+1"   },
  { code: "JP", name: "Japan",                          label: "🇯🇵 Japón",                   dial: "+81"  },
  { code: "JO", name: "Jordan",                         label: "🇯🇴 Jordania",                dial: "+962" },
  { code: "KZ", name: "Kazakhstan",                     label: "🇰🇿 Kazajistán",              dial: "+7"   },
  { code: "KE", name: "Kenya",                          label: "🇰🇪 Kenia",                   dial: "+254" },
  { code: "KG", name: "Kyrgyzstan",                     label: "🇰🇬 Kirguistán",              dial: "+996" },
  { code: "KI", name: "Kiribati",                       label: "🇰🇮 Kiribati",                dial: "+686" },
  { code: "KW", name: "Kuwait",                         label: "🇰🇼 Kuwait",                  dial: "+965" },
  { code: "LA", name: "Laos",                           label: "🇱🇦 Laos",                    dial: "+856" },
  { code: "LS", name: "Lesotho",                        label: "🇱🇸 Lesoto",                  dial: "+266" },
  { code: "LV", name: "Latvia",                         label: "🇱🇻 Letonia",                 dial: "+371" },
  { code: "LB", name: "Lebanon",                        label: "🇱🇧 Líbano",                  dial: "+961" },
  { code: "LR", name: "Liberia",                        label: "🇱🇷 Liberia",                 dial: "+231" },
  { code: "LY", name: "Libya",                          label: "🇱🇾 Libia",                   dial: "+218" },
  { code: "LI", name: "Liechtenstein",                  label: "🇱🇮 Liechtenstein",           dial: "+423" },
  { code: "LT", name: "Lithuania",                      label: "🇱🇹 Lituania",                dial: "+370" },
  { code: "LU", name: "Luxembourg",                     label: "🇱🇺 Luxemburgo",              dial: "+352" },
  { code: "MG", name: "Madagascar",                     label: "🇲🇬 Madagascar",              dial: "+261" },
  { code: "MY", name: "Malaysia",                       label: "🇲🇾 Malasia",                 dial: "+60"  },
  { code: "MW", name: "Malawi",                         label: "🇲🇼 Malaui",                  dial: "+265" },
  { code: "MV", name: "Maldives",                       label: "🇲🇻 Maldivas",                dial: "+960" },
  { code: "ML", name: "Mali",                           label: "🇲🇱 Mali",                    dial: "+223" },
  { code: "MT", name: "Malta",                          label: "🇲🇹 Malta",                   dial: "+356" },
  { code: "MA", name: "Morocco",                        label: "🇲🇦 Marruecos",               dial: "+212" },
  { code: "MU", name: "Mauritius",                      label: "🇲🇺 Mauricio",                dial: "+230" },
  { code: "MR", name: "Mauritania",                     label: "🇲🇷 Mauritania",              dial: "+222" },
  { code: "MX", name: "Mexico",                         label: "🇲🇽 México",                  dial: "+52"  },
  { code: "FM", name: "Micronesia",                     label: "🇫🇲 Micronesia",              dial: "+691" },
  { code: "MD", name: "Moldova",                        label: "🇲🇩 Moldavia",                dial: "+373" },
  { code: "MC", name: "Monaco",                         label: "🇲🇨 Mónaco",                  dial: "+377" },
  { code: "MN", name: "Mongolia",                       label: "🇲🇳 Mongolia",                dial: "+976" },
  { code: "ME", name: "Montenegro",                     label: "🇲🇪 Montenegro",              dial: "+382" },
  { code: "MZ", name: "Mozambique",                     label: "🇲🇿 Mozambique",              dial: "+258" },
  { code: "NA", name: "Namibia",                        label: "🇳🇦 Namibia",                 dial: "+264" },
  { code: "NR", name: "Nauru",                          label: "🇳🇷 Nauru",                   dial: "+674" },
  { code: "NP", name: "Nepal",                          label: "🇳🇵 Nepal",                   dial: "+977" },
  { code: "NI", name: "Nicaragua",                      label: "🇳🇮 Nicaragua",               dial: "+505" },
  { code: "NE", name: "Niger",                          label: "🇳🇪 Níger",                   dial: "+227" },
  { code: "NG", name: "Nigeria",                        label: "🇳🇬 Nigeria",                 dial: "+234" },
  { code: "NO", name: "Norway",                         label: "🇳🇴 Noruega",                 dial: "+47"  },
  { code: "NZ", name: "New Zealand",                    label: "🇳🇿 Nueva Zelanda",           dial: "+64"  },
  { code: "OM", name: "Oman",                           label: "🇴🇲 Omán",                    dial: "+968" },
  { code: "NL", name: "Netherlands",                    label: "🇳🇱 Países Bajos",            dial: "+31"  },
  { code: "PK", name: "Pakistan",                       label: "🇵🇰 Pakistán",                dial: "+92"  },
  { code: "PW", name: "Palau",                          label: "🇵🇼 Palaos",                  dial: "+680" },
  { code: "PA", name: "Panama",                         label: "🇵🇦 Panamá",                  dial: "+507" },
  { code: "PG", name: "Papua New Guinea",               label: "🇵🇬 Papúa Nueva Guinea",      dial: "+675" },
  { code: "PY", name: "Paraguay",                       label: "🇵🇾 Paraguay",                dial: "+595" },
  { code: "PE", name: "Peru",                           label: "🇵🇪 Perú",                    dial: "+51"  },
  { code: "PL", name: "Poland",                         label: "🇵🇱 Polonia",                 dial: "+48"  },
  { code: "PT", name: "Portugal",                       label: "🇵🇹 Portugal",                dial: "+351" },
  { code: "DO", name: "Dominican Republic",             label: "🇩🇴 República Dominicana",    dial: "+1"   },
  { code: "CZ", name: "Czech Republic",                 label: "🇨🇿 República Checa",         dial: "+420" },
  { code: "RW", name: "Rwanda",                         label: "🇷🇼 Ruanda",                  dial: "+250" },
  { code: "RO", name: "Romania",                        label: "🇷🇴 Rumanía",                 dial: "+40"  },
  { code: "RU", name: "Russia",                         label: "🇷🇺 Rusia",                   dial: "+7"   },
  { code: "WS", name: "Samoa",                          label: "🇼🇸 Samoa",                   dial: "+685" },
  { code: "KN", name: "Saint Kitts and Nevis",          label: "🇰🇳 San Cristóbal y Nieves",  dial: "+1"   },
  { code: "SM", name: "San Marino",                     label: "🇸🇲 San Marino",              dial: "+378" },
  { code: "VC", name: "Saint Vincent and the Grenadines", label: "🇻🇨 San Vicente y las Granadinas", dial: "+1" },
  { code: "LC", name: "Saint Lucia",                    label: "🇱🇨 Santa Lucía",             dial: "+1"   },
  { code: "ST", name: "Sao Tome and Principe",          label: "🇸🇹 Santo Tomé y Príncipe",   dial: "+239" },
  { code: "SN", name: "Senegal",                        label: "🇸🇳 Senegal",                 dial: "+221" },
  { code: "RS", name: "Serbia",                         label: "🇷🇸 Serbia",                  dial: "+381" },
  { code: "SC", name: "Seychelles",                     label: "🇸🇨 Seychelles",              dial: "+248" },
  { code: "SL", name: "Sierra Leone",                   label: "🇸🇱 Sierra Leona",            dial: "+232" },
  { code: "SG", name: "Singapore",                      label: "🇸🇬 Singapur",                dial: "+65"  },
  { code: "SY", name: "Syria",                          label: "🇸🇾 Siria",                   dial: "+963" },
  { code: "SO", name: "Somalia",                        label: "🇸🇴 Somalia",                 dial: "+252" },
  { code: "LK", name: "Sri Lanka",                      label: "🇱🇰 Sri Lanka",               dial: "+94"  },
  { code: "ZA", name: "South Africa",                   label: "🇿🇦 Sudáfrica",               dial: "+27"  },
  { code: "SD", name: "Sudan",                          label: "🇸🇩 Sudán",                   dial: "+249" },
  { code: "SS", name: "South Sudan",                    label: "🇸🇸 Sudán del Sur",           dial: "+211" },
  { code: "SE", name: "Sweden",                         label: "🇸🇪 Suecia",                  dial: "+46"  },
  { code: "CH", name: "Switzerland",                    label: "🇨🇭 Suiza",                   dial: "+41"  },
  { code: "SR", name: "Suriname",                       label: "🇸🇷 Surinam",                 dial: "+597" },
  { code: "TH", name: "Thailand",                       label: "🇹🇭 Tailandia",               dial: "+66"  },
  { code: "TZ", name: "Tanzania",                       label: "🇹🇿 Tanzania",                dial: "+255" },
  { code: "TJ", name: "Tajikistan",                     label: "🇹🇯 Tayikistán",              dial: "+992" },
  { code: "TL", name: "Timor-Leste",                    label: "🇹🇱 Timor Oriental",          dial: "+670" },
  { code: "TG", name: "Togo",                           label: "🇹🇬 Togo",                    dial: "+228" },
  { code: "TO", name: "Tonga",                          label: "🇹🇴 Tonga",                   dial: "+676" },
  { code: "TT", name: "Trinidad and Tobago",            label: "🇹🇹 Trinidad y Tobago",       dial: "+1"   },
  { code: "TN", name: "Tunisia",                        label: "🇹🇳 Túnez",                   dial: "+216" },
  { code: "TM", name: "Turkmenistan",                   label: "🇹🇲 Turkmenistán",            dial: "+993" },
  { code: "TR", name: "Turkey",                         label: "🇹🇷 Turquía",                 dial: "+90"  },
  { code: "TV", name: "Tuvalu",                         label: "🇹🇻 Tuvalu",                  dial: "+688" },
  { code: "UA", name: "Ukraine",                        label: "🇺🇦 Ucrania",                 dial: "+380" },
  { code: "UG", name: "Uganda",                         label: "🇺🇬 Uganda",                  dial: "+256" },
  { code: "UY", name: "Uruguay",                        label: "🇺🇾 Uruguay",                 dial: "+598" },
  { code: "UZ", name: "Uzbekistan",                     label: "🇺🇿 Uzbekistán",              dial: "+998" },
  { code: "VU", name: "Vanuatu",                        label: "🇻🇺 Vanuatu",                 dial: "+678" },
  { code: "VE", name: "Venezuela",                      label: "🇻🇪 Venezuela",               dial: "+58"  },
  { code: "VN", name: "Vietnam",                        label: "🇻🇳 Vietnam",                 dial: "+84"  },
  { code: "YE", name: "Yemen",                          label: "🇾🇪 Yemen",                   dial: "+967" },
  { code: "ZM", name: "Zambia",                         label: "🇿🇲 Zambia",                  dial: "+260" },
  { code: "ZW", name: "Zimbabwe",                       label: "🇿🇼 Zimbabue",                dial: "+263" },
];

export const PROFILE_PROFESSIONS = [
  { id: "artista",    name: "Artista",     description: "Cantante, músico o intérprete"       },
  { id: "productor",  name: "Productor",   description: "Productor musical o de audio"         },
  { id: "compositor", name: "Compositor",  description: "Compositor o escritor de canciones"   },
  { id: "otro",       name: "Otro",        description: "Otra profesión musical"               },
];

export const OTHER_PROFESSIONS = [
  "Ingeniero de sonido", "Diseñador de sonido", "Diseñador de audio",
  "Ingeniero de mezcla", "Ingeniero de masterización", "Ingeniero de grabación",
  "Manager musical", "Promotor de eventos", "DJ", "Locutor", "Podcaster",
];

export const PHONE_CODES = [
  { dial: "+1",   label: "🇺🇸 +1"   }, { dial: "+7",   label: "🇷🇺 +7"   },
  { dial: "+20",  label: "🇪🇬 +20"  }, { dial: "+27",  label: "🇿🇦 +27"  },
  { dial: "+30",  label: "🇬🇷 +30"  }, { dial: "+31",  label: "🇳🇱 +31"  },
  { dial: "+32",  label: "🇧🇪 +32"  }, { dial: "+33",  label: "🇫🇷 +33"  },
  { dial: "+34",  label: "🇪🇸 +34"  }, { dial: "+36",  label: "🇭🇺 +36"  },
  { dial: "+39",  label: "🇮🇹 +39"  }, { dial: "+40",  label: "🇷🇴 +40"  },
  { dial: "+41",  label: "🇨🇭 +41"  }, { dial: "+43",  label: "🇦🇹 +43"  },
  { dial: "+44",  label: "🇬🇧 +44"  }, { dial: "+45",  label: "🇩🇰 +45"  },
  { dial: "+46",  label: "🇸🇪 +46"  }, { dial: "+47",  label: "🇳🇴 +47"  },
  { dial: "+48",  label: "🇵🇱 +48"  }, { dial: "+49",  label: "🇩🇪 +49"  },
  { dial: "+51",  label: "🇵🇪 +51"  }, { dial: "+52",  label: "🇲🇽 +52"  },
  { dial: "+53",  label: "🇨🇺 +53"  }, { dial: "+54",  label: "🇦🇷 +54"  },
  { dial: "+55",  label: "🇧🇷 +55"  }, { dial: "+56",  label: "🇨🇱 +56"  },
  { dial: "+57",  label: "🇨🇴 +57"  }, { dial: "+58",  label: "🇻🇪 +58"  },
  { dial: "+60",  label: "🇲🇾 +60"  }, { dial: "+61",  label: "🇦🇺 +61"  },
  { dial: "+62",  label: "🇮🇩 +62"  }, { dial: "+63",  label: "🇵🇭 +63"  },
  { dial: "+64",  label: "🇳🇿 +64"  }, { dial: "+65",  label: "🇸🇬 +65"  },
  { dial: "+66",  label: "🇹🇭 +66"  }, { dial: "+81",  label: "🇯🇵 +81"  },
  { dial: "+82",  label: "🇰🇷 +82"  }, { dial: "+84",  label: "🇻🇳 +84"  },
  { dial: "+86",  label: "🇨🇳 +86"  }, { dial: "+90",  label: "🇹🇷 +90"  },
  { dial: "+91",  label: "🇮🇳 +91"  }, { dial: "+92",  label: "🇵🇰 +92"  },
  { dial: "+93",  label: "🇦🇫 +93"  }, { dial: "+94",  label: "🇱🇰 +94"  },
  { dial: "+95",  label: "🇲🇲 +95"  }, { dial: "+98",  label: "🇮🇷 +98"  },
  { dial: "+212", label: "🇲🇦 +212" }, { dial: "+213", label: "🇩🇿 +213" },
  { dial: "+216", label: "🇹🇳 +216" }, { dial: "+218", label: "🇱🇾 +218" },
  { dial: "+220", label: "🇬🇲 +220" }, { dial: "+221", label: "🇸🇳 +221" },
  { dial: "+222", label: "🇲🇷 +222" }, { dial: "+223", label: "🇲🇱 +223" },
  { dial: "+224", label: "🇬🇳 +224" }, { dial: "+225", label: "🇨🇮 +225" },
  { dial: "+226", label: "🇧🇫 +226" }, { dial: "+227", label: "🇳🇪 +227" },
  { dial: "+228", label: "🇹🇬 +228" }, { dial: "+229", label: "🇧🇯 +229" },
  { dial: "+230", label: "🇲🇺 +230" }, { dial: "+231", label: "🇱🇷 +231" },
  { dial: "+232", label: "🇸🇱 +232" }, { dial: "+233", label: "🇬🇭 +233" },
  { dial: "+234", label: "🇳🇬 +234" }, { dial: "+235", label: "🇹🇩 +235" },
  { dial: "+237", label: "🇨🇲 +237" }, { dial: "+238", label: "🇨🇻 +238" },
  { dial: "+239", label: "🇸🇹 +239" }, { dial: "+240", label: "🇬🇶 +240" },
  { dial: "+241", label: "🇬🇦 +241" }, { dial: "+242", label: "🇨🇬 +242" },
  { dial: "+243", label: "🇨🇩 +243" }, { dial: "+244", label: "🇦🇴 +244" },
  { dial: "+245", label: "🇬🇼 +245" }, { dial: "+248", label: "🇸🇨 +248" },
  { dial: "+249", label: "🇸🇩 +249" }, { dial: "+250", label: "🇷🇼 +250" },
  { dial: "+251", label: "🇪🇹 +251" }, { dial: "+252", label: "🇸🇴 +252" },
  { dial: "+253", label: "🇩🇯 +253" }, { dial: "+254", label: "🇰🇪 +254" },
  { dial: "+255", label: "🇹🇿 +255" }, { dial: "+256", label: "🇺🇬 +256" },
  { dial: "+257", label: "🇧🇮 +257" }, { dial: "+258", label: "🇲🇿 +258" },
  { dial: "+260", label: "🇿🇲 +260" }, { dial: "+261", label: "🇲🇬 +261" },
  { dial: "+262", label: "🇷🇪 +262" }, { dial: "+263", label: "🇿🇼 +263" },
  { dial: "+264", label: "🇳🇦 +264" }, { dial: "+265", label: "🇲🇼 +265" },
  { dial: "+266", label: "🇱🇸 +266" }, { dial: "+267", label: "🇧🇼 +267" },
  { dial: "+268", label: "🇸🇿 +268" }, { dial: "+269", label: "🇰🇲 +269" },
  { dial: "+291", label: "🇪🇷 +291" }, { dial: "+297", label: "🇦🇼 +297" },
  { dial: "+298", label: "🇫🇴 +298" }, { dial: "+299", label: "🇬🇱 +299" },
  { dial: "+350", label: "🇬🇮 +350" }, { dial: "+351", label: "🇵🇹 +351" },
  { dial: "+352", label: "🇱🇺 +352" }, { dial: "+353", label: "🇮🇪 +353" },
  { dial: "+354", label: "🇮🇸 +354" }, { dial: "+355", label: "🇦🇱 +355" },
  { dial: "+356", label: "🇲🇹 +356" }, { dial: "+357", label: "🇨🇾 +357" },
  { dial: "+358", label: "🇫🇮 +358" }, { dial: "+359", label: "🇧🇬 +359" },
  { dial: "+370", label: "🇱🇹 +370" }, { dial: "+371", label: "🇱🇻 +371" },
  { dial: "+372", label: "🇪🇪 +372" }, { dial: "+373", label: "🇲🇩 +373" },
  { dial: "+374", label: "🇦🇲 +374" }, { dial: "+375", label: "🇧🇾 +375" },
  { dial: "+376", label: "🇦🇩 +376" }, { dial: "+377", label: "🇲🇨 +377" },
  { dial: "+378", label: "🇸🇲 +378" }, { dial: "+380", label: "🇺🇦 +380" },
  { dial: "+381", label: "🇷🇸 +381" }, { dial: "+382", label: "🇲🇪 +382" },
  { dial: "+385", label: "🇭🇷 +385" }, { dial: "+386", label: "🇸🇮 +386" },
  { dial: "+387", label: "🇧🇦 +387" }, { dial: "+389", label: "🇲🇰 +389" },
  { dial: "+420", label: "🇨🇿 +420" }, { dial: "+421", label: "🇸🇰 +421" },
  { dial: "+423", label: "🇱🇮 +423" }, { dial: "+500", label: "🇫🇰 +500" },
  { dial: "+501", label: "🇧🇿 +501" }, { dial: "+502", label: "🇬🇹 +502" },
  { dial: "+503", label: "🇸🇻 +503" }, { dial: "+504", label: "🇭🇳 +504" },
  { dial: "+505", label: "🇳🇮 +505" }, { dial: "+506", label: "🇨🇷 +506" },
  { dial: "+507", label: "🇵🇦 +507" }, { dial: "+509", label: "🇭🇹 +509" },
  { dial: "+591", label: "🇧🇴 +591" }, { dial: "+592", label: "🇬🇾 +592" },
  { dial: "+593", label: "🇪🇨 +593" }, { dial: "+594", label: "🇬🇫 +594" },
  { dial: "+595", label: "🇵🇾 +595" }, { dial: "+596", label: "🇲🇶 +596" },
  { dial: "+597", label: "🇸🇷 +597" }, { dial: "+598", label: "🇺🇾 +598" },
  { dial: "+599", label: "🇧🇶 +599" }, { dial: "+670", label: "🇹🇱 +670" },
  { dial: "+672", label: "🇳🇫 +672" }, { dial: "+673", label: "🇧🇳 +673" },
  { dial: "+674", label: "🇳🇷 +674" }, { dial: "+675", label: "🇵🇬 +675" },
  { dial: "+676", label: "🇹🇴 +676" }, { dial: "+677", label: "🇸🇧 +677" },
  { dial: "+678", label: "🇻🇺 +678" }, { dial: "+679", label: "🇫🇯 +679" },
  { dial: "+680", label: "🇵🇼 +680" }, { dial: "+685", label: "🇼🇸 +685" },
  { dial: "+686", label: "🇰🇮 +686" }, { dial: "+688", label: "🇹🇻 +688" },
  { dial: "+689", label: "🇵🇫 +689" }, { dial: "+691", label: "🇫🇲 +691" },
  { dial: "+692", label: "🇲🇭 +692" }, { dial: "+850", label: "🇰🇵 +850" },
  { dial: "+852", label: "🇭🇰 +852" }, { dial: "+853", label: "🇲🇴 +853" },
  { dial: "+855", label: "🇰🇭 +855" }, { dial: "+856", label: "🇱🇦 +856" },
  { dial: "+880", label: "🇧🇩 +880" }, { dial: "+886", label: "🇹🇼 +886" },
  { dial: "+960", label: "🇲🇻 +960" }, { dial: "+961", label: "🇱🇧 +961" },
  { dial: "+962", label: "🇯🇴 +962" }, { dial: "+963", label: "🇸🇾 +963" },
  { dial: "+964", label: "🇮🇶 +964" }, { dial: "+965", label: "🇰🇼 +965" },
  { dial: "+966", label: "🇸🇦 +966" }, { dial: "+967", label: "🇾🇪 +967" },
  { dial: "+968", label: "🇴🇲 +968" }, { dial: "+971", label: "🇦🇪 +971" },
  { dial: "+972", label: "🇮🇱 +972" }, { dial: "+973", label: "🇧🇭 +973" },
  { dial: "+974", label: "🇶🇦 +974" }, { dial: "+975", label: "🇧🇹 +975" },
  { dial: "+976", label: "🇲🇳 +976" }, { dial: "+977", label: "🇳🇵 +977" },
  { dial: "+992", label: "🇹🇯 +992" }, { dial: "+993", label: "🇹🇲 +993" },
  { dial: "+994", label: "🇦🇿 +994" }, { dial: "+995", label: "🇬🇪 +995" },
  { dial: "+996", label: "🇰🇬 +996" }, { dial: "+998", label: "🇺🇿 +998" },
];
