name: "Deploy to S3",
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2

    - name: 'SetUp Node'
      uses: actions/setup-node@v3 
      with:
        node-version: 20

    - name: 'Install Dependencies'
      run: npm install

    - name: 'Build'
      run: npm run build

    - name: 'Deploy to S3'
      uses: jakejarvis/s3-sync-action@master
      with:
        aws-key: ${{secrets.ACCESS_AWS}}
        aws-secret: ${{secrets.KEY_AWS}}
        aws-region: "us-east-2"
        source-dir: "build"
        dest-dir: "splitme"

